#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cloc
Version  : 1.82
Release  : 3
URL      : https://github.com/AlDanial/cloc/archive/1.82.tar.gz
Source0  : https://github.com/AlDanial/cloc/archive/1.82.tar.gz
Summary  : Count lines of code
Group    : Development/Tools
License  : GPL-2.0
Requires: cloc-bin = %{version}-%{release}
Requires: cloc-license = %{version}-%{release}
BuildRequires : buildreq-golang
BuildRequires : buildreq-qmake
Patch1: 0001-Add-Makefile.patch

%description
----------------------------------------------------------------
Count physical lines of source code in the given files (may be
archives such as compressed tarballs or zip files) and/or recursively
below the given directories.  Given two directories or archive
files, it can compute differences of source code and comments
between the code bases.

%package bin
Summary: bin components for the cloc package.
Group: Binaries
Requires: cloc-license = %{version}-%{release}

%description bin
bin components for the cloc package.


%package license
Summary: license components for the cloc package.
Group: Default

%description license
license components for the cloc package.


%prep
%setup -q -n cloc-1.82
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557667777
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1557667777
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cloc
cp LICENSE %{buildroot}/usr/share/package-licenses/cloc/LICENSE
cp Unix/COPYING %{buildroot}/usr/share/package-licenses/cloc/Unix_COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cloc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cloc/LICENSE
/usr/share/package-licenses/cloc/Unix_COPYING
