#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cloc
Version  : 1.90
Release  : 7
URL      : https://github.com/AlDanial/cloc/archive/v1.90/cloc-1.90.tar.gz
Source0  : https://github.com/AlDanial/cloc/archive/v1.90/cloc-1.90.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: cloc-bin = %{version}-%{release}
Requires: cloc-license = %{version}-%{release}
BuildRequires : buildreq-golang
BuildRequires : buildreq-meson
BuildRequires : buildreq-qmake
Patch1: 0001-Add-Makefile.patch

%description
----------------------------------------------------------------
Count physical lines of source code in the given files (may be
archives such as compressed tarballs or zip files) and/or recursively
below the given directories.  Given two directories or archive
files, it can compute differences of source code and comments
between the code bases.

%package bin
Summary: bin components for the cloc package.
Group: Binaries
Requires: cloc-license = %{version}-%{release}

%description bin
bin components for the cloc package.


%package license
Summary: license components for the cloc package.
Group: Default

%description license
license components for the cloc package.


%prep
%setup -q -n cloc-1.90
cd %{_builddir}/cloc-1.90
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1619996125
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1619996125
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cloc
cp %{_builddir}/cloc-1.90/LICENSE %{buildroot}/usr/share/package-licenses/cloc/30a6e0a424471d8ac874b5616dd5a18c45fd6046
cp %{_builddir}/cloc-1.90/Unix/COPYING %{buildroot}/usr/share/package-licenses/cloc/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cloc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cloc/30a6e0a424471d8ac874b5616dd5a18c45fd6046
/usr/share/package-licenses/cloc/4cc77b90af91e615a64ae04893fdffa7939db84c
